<?php

namespace App\Services\Export;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class PdfExportService
{
    /**
     * Generate corporate print-ready HTML file and save to storage.
     * Returns the relative storage path.
     */
    public function generate(string $reportName, array $columns, $data): string
    {
        $fileName = 'reports/' . Str::slug($reportName) . '_' . time() . '.html';

        $html = '<!DOCTYPE html>';
        $html .= '<html lang="en">';
        $html .= '<head>';
        $html .= '<meta charset="UTF-8">';
        $html .= '<title>' . htmlspecialchars($reportName) . '</title>';
        $html .= '<style>';
        $html .= 'body { font-family: "Inter", "Segoe UI", Roboto, sans-serif; color: #1e293b; background-color: #ffffff; margin: 0; padding: 30px; font-size: 13px; line-height: 1.5; }';
        $html .= '.header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #4f46e5; padding-bottom: 15px; margin-bottom: 25px; }';
        $html .= '.header h1 { margin: 0; font-size: 22px; color: #1e3a8a; font-weight: 800; }';
        $html .= '.header p { margin: 2px 0 0 0; color: #64748b; font-size: 11px; text-transform: uppercase; }';
        $html .= 'table { width: 100%; border-collapse: collapse; margin-top: 15px; }';
        $html .= 'th { background-color: #f1f5f9; color: #334155; font-weight: 700; border-bottom: 2px solid #cbd5e1; padding: 10px 12px; text-align: left; }';
        $html .= 'td { border-bottom: 1px solid #e2e8f0; padding: 10px 12px; text-align: left; }';
        $html .= 'tr:nth-child(even) { background-color: #f8fafc; }';
        $html .= '.footer { margin-top: 40px; border-top: 1px solid #e2e8f0; padding-top: 15px; display: flex; justify-content: space-between; font-size: 11px; color: #64748b; }';
        $html .= '@media print { body { padding: 0; } .no-print { display: none; } }';
        $html .= '</style>';
        $html .= '</head>';
        $html .= '<body>';
        $html .= '<div class="no-print" style="margin-bottom: 20px; text-align: right;">';
        $html .= '<button onclick="window.print()" style="background-color: #4f46e5; color: white; border: none; padding: 8px 16px; border-radius: 4px; cursor: pointer; font-weight: 600;">Print Report</button>';
        $html .= '</div>';
        $html .= '<div class="header">';
        $html .= '<div>';
        $html .= '<h1>' . htmlspecialchars($reportName) . '</h1>';
        $html .= '<p>Enterprise HRMS Reporting Portal</p>';
        $html .= '</div>';
        $html .= '<div style="text-align: right;">';
        $html .= '<strong>Date:</strong> ' . now()->format('F d, Y') . '<br>';
        $html .= '<strong>Time:</strong> ' . now()->format('h:i A') . '';
        $html .= '</div>';
        $html .= '</div>';
        $html .= '<table>';
        $html .= '<thead><tr>';
        
        foreach (array_values($columns) as $label) {
            $html .= '<th>' . htmlspecialchars($label) . '</th>';
        }
        $html .= '</tr></thead>';
        $html .= '<tbody>';

        foreach ($data as $row) {
            $html .= '<tr>';
            foreach (array_keys($columns) as $key) {
                $val = $this->resolveValue($row, $key);
                $html .= '<td>' . htmlspecialchars((string) $val) . '</td>';
            }
            $html .= '</tr>';
        }

        $html .= '</tbody>';
        $html .= '</table>';
        $html .= '<div class="footer">';
        $html .= '<span>Confidential - For Internal HR Use Only</span>';
        $html .= '<span>Generated by HRMS System Engine</span>';
        $html .= '</div>';
        $html .= '</body>';
        $html .= '</html>';

        Storage::disk('public')->put($fileName, $html);

        return $fileName;
    }

    /**
     * Resolve nested relationship value.
     */
    protected function resolveValue($row, string $key)
    {
        if (strpos($key, '.') !== false) {
            $parts = explode('.', $key);
            $current = $row;
            foreach ($parts as $part) {
                if (is_object($current)) {
                    $current = $current->{$part};
                } elseif (is_array($current)) {
                    $current = $current[$part] ?? null;
                } else {
                    return '';
                }
            }
            return $current ?? '';
        }

        return $row->{$key} ?? '';
    }
}
